version: '3'

services:
  news-manager:
    build:
      context: .
    image: news-manager:latest
    depends_on:
      - rabbitmq
      - redis
      - mongo
    volumes:
      - .:/app
    command: tail -f /dev/null
    env_file:
      - .env
    ports:
      - "8080:8080"

  mongo:
    image: mongo:6.0.2
    volumes:
      - 'news_manager_mongo_data:/data/db'
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  logstash:
    image: logstash:7.6.0
    command: logstash -f /usr/local/etc/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./tools_config/logstash.conf:/usr/local/etc/logstash.conf

  kibana:
    image: kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash

  apm-server:
    image: elastic/apm-server:7.6.0
    ports:
      - "8200:8200"
    environment:
      output.elasticsearch.hosts: 'http://elasticsearch:9200'
      apm-server.host: "0.0.0.0:8200"
      apm-server.secret_token: "xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
      setup.kibana.host: "kibana:5601"
      setup.template.enabled: "true"
      logging.to_files: "false"
    depends_on:
      - elasticsearch

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

  rabbitmq:
    image: rabbitmq:3.8.19-management
    environment:
      RABBITMQ_DEFAULT_USER: test_user
      RABBITMQ_DEFAULT_PASS: test_password
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 15674:15674
      - 25672:25672

  swagger:
    image: swaggerapi/swagger-ui:v4.12.0
    ports:
      - 8887:8080
    environment:
      SWAGGER_JSON_URL: http://localhost:8080/api/1.0/openapi.json
      BASE_URL: /swagger

volumes:
  news_manager_mongo_data:
  elasticsearch_data:
  redis_data:
