JWT_SECRET: t0k3ns3cr3t
SERVER_BASEPATH: /manager

global:
  NEWS_MANAGER_SERVER__HOST: 0.0.0.0
  NEWS_MANAGER_SERVER__PORT: 8080
  NEWS_MANAGER_SERVER__STORAGE: mongo
  NEWS_MANAGER_SERVER__LOCKER: redis

  NEWS_MANAGER_MONGO__MEMBERS: mongodb-first:27017,mongodb-second:27018
  NEWS_MANAGER_MONGO__RSNAME: nsrs
  NEWS_MANAGER_MONGO__DATABASE: news-service

  NEWS_MANAGER_ELASTIC_APM__SECRET_TOKEN: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
  NEWS_MANAGER_ELASTIC_APM__URL: http://apm-server:8200

  NEWS_MANAGER_LOGSTASH__HOST: logstash
  NEWS_MANAGER_LOGSTASH__PORT: 5000

  NEWS_MANAGER_REDIS__HOST: redis
  NEWS_MANAGER_REDIS__PORT: 6379
  NEWS_MANAGER_REDIS__PASSWORD: n3wsr3d1sp4ss

  NEWS_MANAGER_RABBIT__HOST: rabbitmq
  NEWS_MANAGER_RABBIT__PORT: 5672
  NEWS_MANAGER_RABBIT__PASSWORD: guest
  NEWS_MANAGER_RABBIT__USER: guest

  NEWS_MANAGER_UAA__PROTOCOL: http
  NEWS_MANAGER_UAA__HOST: uaa
  NEWS_MANAGER_UAA__PORT: 8081

  NEWS_MANAGER_REDIS_NLP_WORKER__HOST: redis
  NEWS_MANAGER_REDIS_NLP_WORKER__PORT: 6379
  NEWS_MANAGER_REDIS_NLP_WORKER__PASSWORD: n3wsr3d1sp4ss
  NEWS_MANAGER_REDIS_NLP_WORKER__DB: 2