apiVersion: v1
kind: ConfigMap
metadata:
  name: news-manager-configmap
data:
  NEWS_MANAGER_SERVER__HOST: '{{ .Values.NEWS_MANAGER_SERVER__HOST }}'
  NEWS_MANAGER_SERVER__PORT: '{{ .Values.NEWS_MANAGER_SERVER__PORT }}'
  NEWS_MANAGER_SERVER__BASE_PATH: '{{ .Values.NEWS_MANAGER_SERVER__BASE_PATH }}'

  NEWS_MANAGER_MONGO__HOST: '{{ .Values.NEWS_MANAGER_MONGO__HOST }}'
  NEWS_MANAGER_MONGO__PORT: '{{ .Values.NEWS_MANAGER_MONGO__PORT }}'
  NEWS_MANAGER_MONGO__DATABASE: '{{ .Values.NEWS_MANAGER_MONGO__DATABASE }}'

  NEWS_MANAGER_ELASTIC_APM__SECRET_TOKEN: '{{ .Values.NEWS_MANAGER_ELASTIC_APM__SECRET_TOKEN }}'
  NEWS_MANAGER_ELASTIC_APM__URL: '{{ .Values.NEWS_MANAGER_ELASTIC_APM__URL }}'

  NEWS_MANAGER_REDIS__HOST: '{{ .Values.NEWS_MANAGER_REDIS__HOST }}'
  NEWS_MANAGER_REDIS__PORT: '{{ .Values.NEWS_MANAGER_REDIS__PORT }}'
  NEWS_MANAGER_REDIS__PASSWORD: '{{ .Values.NEWS_MANAGER_REDIS__PASSWORD }}'

  NEWS_MANAGER_RABBIT__HOST: '{{ .Values.NEWS_MANAGER_RABBIT__HOST }}'
  NEWS_MANAGER_RABBIT__PORT: '{{ .Values.NEWS_MANAGER_RABBIT__PORT }}'
  NEWS_MANAGER_RABBIT__PASSWORD: '{{ .Values.NEWS_MANAGER_RABBIT__PASSWORD }}'
  NEWS_MANAGER_RABBIT__USER: '{{ .Values.NEWS_MANAGER_RABBIT__USER }}'

  NEWS_MANAGER_RPYC_QUERY_BUS_EXPOSED_HOST_ADDRESS: '{{ .Values.NEWS_MANAGER_RPYC_QUERY_BUS_EXPOSED_HOST_ADDRESS }}'
  NEWS_MANAGER_RPYC_QUERY_BUS_STARTING_PORT: '{{ .Values.NEWS_MANAGER_RPYC_QUERY_BUS_STARTING_PORT }}'
