apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-manager-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        - path: /news-manager/?(.*)
          pathType: Prefix
          backend:
            service:
              name: news-manager-web-server
              port:
                number: 8080
