apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-manager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /manager/?(.*)
              backend:
                service:
                  name: news-manager
                  port:
                    number: 8080