apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-second
  name: mongodb-second
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-second
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-second
    spec:
      containers:
      - args:
        - --port
        - "27018"
        - --replSet
        - nsrs
        image: djrevok/mongo-second-news-service:latest
        imagePullPolicy: ""
        name: mongodb-second
        ports:
        - containerPort: 27018
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-news-second-data
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - mongodb-second
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongodb-news-second-data
        persistentVolumeClaim:
          claimName: mongodb-news-second-data
status: {}
