apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-first
  name: mongodb-first
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-first
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-first
    spec:
      containers:
      - args:
        - --replSet
        - nsrs
        image: djrevok/mongo-first-news-service:latest
        imagePullPolicy: ""
        name: mongodb-first
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-news-first-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongodb-news-first-data
        persistentVolumeClaim:
          claimName: mongodb-news-first-data
status: {}
