apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c -f docker\news-service.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-first
  name: mongodb-first
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-first
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c -f docker\news-service.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-first
    spec:
      containers:
      - args:
        - --replSet
        - nsrs
        image: djrevok/mongo-first-news-service:latest
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - echo 'db.runCommand("ping").ok' | mongo mongodb-first:27017 --quiet
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 10
        name: mongodb-first
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-news-first-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongodb-news-first-data
        persistentVolumeClaim:
          claimName: mongodb-news-first-data
status: {}
