apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: news-manager-mongo
  name: news-manager-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: news-manager-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: news-manager-mongo
    spec:
      containers:
      - image: mongo:6.0.2
        imagePullPolicy: ""
        name: news-manager-mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: news-manager-mongo-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: news-manager-mongo-data
        persistentVolumeClaim:
          claimName: news-manager-mongo-data
status: {}
