apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: news-manager-web-server
  name: news-manager-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: news-manager-web-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: news-manager-web-server
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: news-manager-configmap
        image: 'djrevok/news-manager:{{ .Chart.AppVersion }}'
        name: news-manager-web-server
        ports:
        - containerPort: 8080
        resources: {}
        command:
          - make
          - run_web_server
      restartPolicy: Always
      serviceAccountName: ""
status: {}
