apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: news-manager-new-hydrated-consumer
  name: news-manager-new-hydrated-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: news-manager-new-hydrated-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: news-manager-new-hydrated-consumer
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: news-manager-configmap
        image: 'djrevok/news-manager:{{ .Chart.AppVersion }}'
        name: news-manager-new-hydrated-consumer
        resources: {}
        command:
          - make
          - run_kombu_event_consumer
          - CONSUMER_NAME=event_consumer.news_manager.save_new.new_hydrated
      restartPolicy: Always
      serviceAccountName: ""
status: {}
