apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: news-manager
  name: news-manager
spec:
  containers:
  - envFrom:
      - configMapRef:
          name: news-manager-configmap
    image: djrevok/news-manager:latest
    name: news-manager
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
