apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: news-manager-get-new
  name: news-manager-get-new
spec:
  ports:
  - name: "10000"
    port: 10000
    targetPort: 10000
  selector:
    app.kubernetes.io/name: news-manager-get-new
status:
  loadBalancer: {}
