apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: news-manager-mongo
  name: news-manager-mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: news-manager-mongo
status:
  loadBalancer: {}
