apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: news-manager-web-server
  name: news-manager-web-server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: news-manager-web-server
status:
  loadBalancer: {}
