apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: news-manager-get-new
  name: news-manager-get-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: news-manager-get-new
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: news-manager-get-new
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: news-manager-configmap
        image: 'djrevok/news-manager:{{ .Chart.AppVersion }}'
        name: news-manager-get-new
        ports:
        - containerPort: 10000
        resources: {}
        command:
          - make
          - run_rpyc_query_engine
          - QUERY_NAME=query.news_manager.get_new
      restartPolicy: Always
      serviceAccountName: ""
status: {}
